# Generated by Django 5.2.6 on 2025-09-08 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0001_initial'),
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('fecha_baja', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='alumno.alumno', verbose_name='Alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='materia.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('alumno', 'materia')},
            },
        ),
    ]
