# Generated by Django 5.2.6 on 2025-09-08 11:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Materia')),
                ('codigo', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato: ABC123', regex='^[A-Z]{2,4}\\d{3,4}$')], verbose_name='Código')),
                ('año', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Año')),
                ('cuatrimestre', models.PositiveIntegerField(choices=[(1, 'Primer Cuatrimestre'), (2, 'Segundo Cuatrimestre')], verbose_name='Cuatrimestre')),
                ('cupo_maximo', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Cupo Máximo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='carrera.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['carrera', 'año', 'cuatrimestre', 'nombre'],
                'unique_together': {('carrera', 'codigo')},
            },
        ),
    ]
